kind: pipeline
name: Excalibur-kernel

clone:
  depth: 1

steps:
- name: Building
  image: fadlyas/kernel_dockerfile
  environment:
    bot_token:
      from_secret: bot_token
    chat_id:
      from_secret: chat_id
  commands:
  - bash build.sh
